### ISSUE TITLE
Обратная связь / Feedback

### ISSUE THREAD

**Issue by Antosik** [Antosik/lol-guilds-client#36]

**Comment by yellowcherry21** [comment]
"Пригласить всех" - просто имба!

**Comment by impostorby** [comment]
Перестало работать, пишет 
> Клиент League of Legends не запущен!
Можно фикс какой?

**Comment by Antosik** [comment]
> Перестало работать, пишет
> 
> > Клиент League of Legends не запущен!
> 
> Можно фикс какой?

@impostorby, скоро 1.0.0 выпустим 😃 

По проблеме - можешь отписать [мне](https://discordapp.com/users/136113572903124992) в Discord'e?

**Comment by impostorby** [comment]
> 
> 
> Перестало работать, пишет
> 
> > Клиент League of Legends не запущен!
> 
> Можно фикс какой?

Исправилось путём запуска от имени администратора как клиента так и League Guilds Client
