### ISSUE TITLE
Слияния страниц "рейтинг" и "текущий сезон"

### ISSUE THREAD

**Issue by AiDGit** [Antosik/lol-guilds-client#75]
Предлагаю объединить страницы и на страницу "текущий сезон" вынести личный рейтинг игрока в гильдии, вместо позиции гильдии в общем рейтинге, т.к. происходит дублирование информации со страницы "рейтинг".

**Comment by Antosik** [comment]
Обсудили в личке и решили оставить как есть.
Для отображения личной позиции в рейтинге гильдии добавится строчка в раздел "Текущий сезон"
