### ISSUE TITLE
Invite for party is comming even if the player in the game currently

### ISSUE THREAD

**Issue by ekviy** [Antosik/lol-guilds-client#83]
Hi,

The guys from my guilde are telling that they are getting invites even if they are in game and this is distrubing.

How to reproduce:
1. Almost all people from guild are not in friend list.
2. Press button "Пригласить всех"

**Comment by ekviy** [comment]
Извините за беспокойство, а есть какие-то примерное мысли, когда этот баг может быть пофикшен? А то мне в гильдии запрещают ей пользоваться, потому что во время игры звуковое оповещение о инвайте приходит.

**Comment by Antosik** [comment]
Привет, @ekviy!
Спасибо за репорт бага с:

В данный момент я нахожусь на карантине, поэтому не могу точно сказать, когда будет следующее обновление :с

По багу:
Мы знаем об этом баге, но пока нет явного (100%-ного) решения. Есть пара вариантов и сейчас они на обсуждении.

Как только решим, какой из путей использовать - я отпишу.

Ещё раз спасибо за отзыв!

**Comment by Antosik** [comment]
Привет, @ekviy!

Касательно инвайтов - отписали Riot Games о данном баге.
В #94, в качестве временной меры добавили выпадушку для выбора типа приглашения - по умолчанию "Пригласить друзей".

**Comment by ekviy** [comment]
Добрый день @Antosik ,
Спасибо за апдейт. Рад видеть, что работа какая-то осуществляется в направлении фикса.
